"""
********************************************************************************
* Copyright (c) 2026 the Qrisp authors
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License 2.0 which is available at
* http://www.eclipse.org/legal/epl-2.0.
*
* This Source Code may also be made available under the following Secondary
* Licenses when the conditions for such availability set forth in the Eclipse
* Public License, v. 2.0 are satisfied: GNU General Public License, version 2
* with the GNU Classpath Exception which is
* available at https://www.gnu.org/software/classpath/license.html.
*
* SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
********************************************************************************
"""

import pytest
from qrisp import QuantumFloat



@pytest.mark.parametrize("signed", [True, False])
def test_negative_encoding(signed):
    """Test negative encoding: signed accepts, unsigned raises error."""
    qf = QuantumFloat(3, signed=signed)

    if signed:
        index = qf.encoder(-2)
        decoded_value = qf.decoder(index)
        assert decoded_value == -2
    else:
        with pytest.raises(
            ValueError,
            match="Tried to encode negative number in an unsigned QuantumFloat",
        ):
            qf.encoder(-2)


@pytest.mark.parametrize(
    "msize,exponent,signed,min_value",
    [
        (3, 0, True, -8),
        (4, 0, True, -16),
        (2, 0, True, -4),
        (3, 0, True, -2),
        (3, -1, True, -1.5),
        (4, -2, True, -0.75),
        (2, 2, True, -4),
    ],
)
def test_signed_minimum_value(msize, exponent, signed, min_value):
    """Test signed QuantumFloat encodes its minimum value."""
    qf = QuantumFloat(msize, exponent=exponent, signed=signed)
    index = qf.encoder(min_value)
    assert qf.decoder(index) == min_value


@pytest.mark.parametrize("signed", [True, False])
def test_boundary_zero_works(signed):
    """Test that zero encodes correctly for both signed and unsigned QuantumFloats."""
    qf = QuantumFloat(3, exponent=0, signed=signed)
    index = qf.encoder(0)
    assert qf.decoder(index) == 0


@pytest.mark.parametrize("signed", [True, False])
def test_encode_method_uses_encoder_validation(signed):
    """Test that qf[:] = value uses encoder validation."""
    qf = QuantumFloat(3, signed=signed)

    if signed:
        qf[:] = -2
        result = qf.get_measurement()
        assert -2 in result
    else:
        with pytest.raises(
            ValueError,
            match="Tried to encode negative number in an unsigned QuantumFloat",
        ):
            qf[:] = -2


@pytest.mark.parametrize(
    "msize,exponent,signed",
    [
        (3, -1, True),
        (3, -1, False),
        (4, 0, True),
        (4, 0, False),
    ],
)
def test_decoder_generates_all_valid_values(msize, exponent, signed):
    """Test encoder will correctly accept values generated by the decoder."""
    qf = QuantumFloat(msize, exponent=exponent, signed=signed)

    for i in range(2**qf.size):
        value = qf.decoder(i)

        if not signed:
            assert value >= 0

        encoded_i = qf.encoder(value)
        assert encoded_i == i


@pytest.mark.parametrize("signed", [True, False])
def test_roundtrip_consistency_property(signed):
    """Test encoder(decoder(i)) == i (fundamental inverse property)."""
    qf = QuantumFloat(4, exponent=-1, signed=signed)

    for i in range(2**qf.size):
        value = qf.decoder(i)
        re_encoded = qf.encoder(value)
        assert re_encoded == i


@pytest.mark.parametrize(
    "msize,exponent,signed,out_of_bounds_value",
    [
        (3, 0, True, 10),
        (3, 0, False, 10),
        (2, 0, True, -10),
        (2, -4, False, 3),
    ],
)
def test_encoder_rejects_out_of_bounds_values(
    msize, exponent, signed, out_of_bounds_value
):
    """Test that encoder rejects values outside representable range."""
    qf = QuantumFloat(msize, exponent=exponent, signed=signed)

    with pytest.raises(ValueError, match="Not enough qubits to encode value"):
        qf.encoder(out_of_bounds_value)
