version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependabot-dependency-upgrade"
    allow:
      - dependency-type: "all"
    groups:
      actions:
        patterns:
          - "*"
        applies-to: "version-updates"
      actions-security:
        patterns:
          - "*"
        applies-to: "security-updates"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependabot-dependency-upgrade"
    allow:
      - dependency-type: "all"
    groups:
      pip-dependencies:
        patterns:
          - "*"
        applies-to: "version-updates"
      pip-security:
        patterns:
          - "*"
        applies-to: "security-updates"
