# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
early_access: false
reviews:
  profile: "assertive"
  high_level_summary: true
  poem: false
  review_status: false
