"""********************************************************************************
* Copyright (c) 2026 the Qrisp authors
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License 2.0 which is available at
* http://www.eclipse.org/legal/epl-2.0.
*
* This Source Code may also be made available under the following Secondary
* Licenses when the conditions for such availability set forth in the Eclipse
* Public License, v. 2.0 are satisfied: GNU General Public License, version 2
* with the GNU Classpath Exception which is
* available at https://www.gnu.org/software/classpath/license.html.
*
* SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
********************************************************************************
"""

# Stub that redirects to JAX's MLIR infrastructure
from jaxlib.mlir.dialects._ods_common import *
from jaxlib.mlir.dialects._ods_common import _cext as _jaxlib_cext


class _GlobalsCompat:
    """Forwards to jaxlib's ``_cext.globals``, filling in APIs it does not have yet.

    ``_jasp_ops_gen`` is generated by ``mlir-tblgen`` but executed against the
    MLIR runtime bundled in jaxlib, so a file generated with a newer LLVM than
    jaxlib's can call into APIs that runtime does not provide.
    """

    def __init__(self, wrapped):
        object.__setattr__(self, "_wrapped", wrapped)

    def __getattr__(self, name):
        return getattr(self._wrapped, name)

    def register_traceback_file_exclusion(self, *args, **kwargs):
        """Exclude a file from rendered tracebacks -- a no-op if unsupported.

        Emitted by LLVM 22 and newer at the top of the generated bindings.  It
        only affects how tracebacks are prettified, so skipping it costs
        nothing but slightly noisier stack traces.
        """


class _CExtCompat:
    """Forwards to jaxlib's MLIR C extension with a patched ``globals``."""

    def __init__(self, wrapped):
        object.__setattr__(self, "_wrapped", wrapped)
        object.__setattr__(self, "globals", _GlobalsCompat(wrapped.globals))

    def __getattr__(self, name):
        return getattr(self._wrapped, name)


# Wrap only when jaxlib's runtime is missing something the bindings expect, so
# that the plain jaxlib objects are used as soon as it catches up.
if hasattr(_jaxlib_cext.globals, "register_traceback_file_exclusion"):
    _cext = _jaxlib_cext
else:
    _cext = _CExtCompat(_jaxlib_cext)
