"""
********************************************************************************
* Copyright (c) 2026 the Qrisp authors
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License 2.0 which is available at
* http://www.eclipse.org/legal/epl-2.0.
*
* This Source Code may also be made available under the following Secondary
* Licenses when the conditions for such availability set forth in the Eclipse
* Public License, v. 2.0 are satisfied: GNU General Public License, version 2
* with the GNU Classpath Exception which is
* available at https://www.gnu.org/software/classpath/license.html.
*
* SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
********************************************************************************
"""

"""
xDSL dialect definitions for the CUDA-Q Quake dialect (memory-semantics mode).

Only the ops and types needed for the Jasp→Quake lowering are defined here.
All gate ops share the same operand/result structure and a common print method;
individual subclasses are generated by :func:`_mk_gate_cls`.

References
----------
https://nvidia.github.io/cuda-quantum/latest/specification/quake-dialect.html
"""


from typing import Sequence

from xdsl.dialects.builtin import (
    ArrayAttr,
    FunctionType,
    StringAttr,
    i64,
    f64,
    i1,
    i32,
)
from xdsl.ir import (
    Attribute,
    Dialect,
    ParametrizedAttribute,
    SSAValue,
    TypeAttribute,
)
from xdsl.irdl import (
    AnyAttr,
    AttrSizedOperandSegments,
    IRDLOperation,
    irdl_attr_definition,
    irdl_op_definition,
    operand_def,
    result_def,
    var_operand_def,
    var_result_def,
)
from xdsl.printer import Printer

# ---------------------------------------------------------------------------
# Types
# ---------------------------------------------------------------------------


@irdl_attr_definition
class QuakeRefType(ParametrizedAttribute, TypeAttribute):
    """Quake qubit reference type ``!quake.ref`` (memory semantics)."""

    name = "quake.ref"


@irdl_attr_definition
class QuakeVeqType(ParametrizedAttribute, TypeAttribute):
    """Quake qubit-register reference type ``!quake.veq<?>`` (dynamic size)."""

    name = "quake.veq"

    def print_parameters(self, printer: Printer) -> None:
        printer.print_string("<?>")


@irdl_attr_definition
class QuakeMeasureType(ParametrizedAttribute, TypeAttribute):
    """Quake single-measurement result type ``!quake.measure``."""

    name = "quake.measure"


# Shorthand aliases used in operand constraints
_QubitOrVeq = AnyAttr()  # accepts both QuakeRefType and QuakeVeqType


# ---------------------------------------------------------------------------
# Memory-management ops
# ---------------------------------------------------------------------------


@irdl_op_definition
class AllocaRefOp(IRDLOperation):
    """Allocate a single qubit: ``quake.alloca !quake.ref``."""

    name = "quake.alloca"
    result = result_def(QuakeRefType)

    def __init__(self) -> None:
        super().__init__(result_types=[QuakeRefType()])

    def print(self, printer: Printer) -> None:
        printer.print_string(" !quake.ref")


@irdl_op_definition
class AllocaVeqOp(IRDLOperation):
    """Allocate *n* qubits: ``quake.alloca !quake.veq<?>[%n : i64]``."""

    name = "quake.alloca"
    size = operand_def(i64)
    result = result_def(QuakeVeqType)

    def __init__(self, size: SSAValue) -> None:
        super().__init__(operands=[size], result_types=[QuakeVeqType()])

    def print(self, printer: Printer) -> None:
        printer.print_string(" !quake.veq<?>[")
        printer.print_ssa_value(self.size)
        printer.print_string(" : i64]")


@irdl_op_definition
class DeallocOp(IRDLOperation):
    """Deallocate a qubit reference: ``quake.dealloc %ref``."""

    name = "quake.dealloc"
    qubits = operand_def(AnyAttr())

    def __init__(self, qubits: SSAValue) -> None:
        super().__init__(operands=[qubits])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_ssa_value(self.qubits)
        printer.print_string(" : ")
        printer.print_attribute(self.qubits.type)


@irdl_op_definition
class ExtractRefOp(IRDLOperation):
    """Extract a qubit by index.

    Assembly format (CUDA-Q Quake dialect functional-type)::

        %ref = quake.extract_ref %veq[%i] : (!quake.veq<?>, i64) -> !quake.ref

    The CUDA-Q Quake spec defines ``extract_ref``'s index as
    ``Optional<AnySignlessIntegerOrIndex>`` — accepting ``i32``, ``i64``, or
    ``index`` type.  Using ``AnyAttr()`` here keeps the xDSL constraint open so
    the Jasp pipeline (which produces ``i64`` indices) works without an explicit
    cast.  The printer always includes the actual index type in the output.
    """

    name = "quake.extract_ref"
    veq = operand_def(QuakeVeqType)
    index = operand_def(AnyAttr())  # AnySignlessIntegerOrIndex: i32, i64, or index
    result = result_def(QuakeRefType)

    def __init__(self, veq: SSAValue, index: SSAValue) -> None:
        super().__init__(operands=[veq, index], result_types=[QuakeRefType()])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_ssa_value(self.veq)
        printer.print_string("[")
        printer.print_ssa_value(self.index)
        printer.print_string("] : (")
        printer.print_attribute(self.veq.type)
        printer.print_string(", ")
        printer.print_attribute(self.index.type)
        printer.print_string(") -> !quake.ref")


@irdl_op_definition
class VeqSizeOp(IRDLOperation):
    """Return the size of a veq: ``quake.veq_size %veq : !quake.veq<?> -> i64``."""

    name = "quake.veq_size"
    veq = operand_def(QuakeVeqType)
    result = result_def(i64)

    def __init__(self, veq: SSAValue) -> None:
        super().__init__(operands=[veq], result_types=[i64])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_ssa_value(self.veq)
        printer.print_string(" : (!quake.veq<?>) -> i64")


@irdl_op_definition
class SubVeqOp(IRDLOperation):
    """Slice a veq: ``quake.subveq %veq, %lo, %hi : (!quake.veq<?>, i64, i64) -> !quake.veq<?>``."""

    name = "quake.subveq"
    veq = operand_def(QuakeVeqType)
    lo = operand_def(i64)
    hi = operand_def(i64)
    result = result_def(QuakeVeqType)

    def __init__(self, veq: SSAValue, lo: SSAValue, hi: SSAValue) -> None:
        super().__init__(operands=[veq, lo, hi], result_types=[QuakeVeqType()])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_ssa_value(self.veq)
        printer.print_string(", ")
        printer.print_ssa_value(self.lo)
        printer.print_string(", ")
        printer.print_ssa_value(self.hi)
        # Use functional-type format: (veq_type, lo_type, hi_type) -> result_type
        printer.print_string(" : (")
        printer.print_attribute(self.veq.type)
        printer.print_string(", ")
        printer.print_attribute(self.lo.type)
        printer.print_string(", ")
        printer.print_attribute(self.hi.type)
        printer.print_string(") -> !quake.veq<?>")


@irdl_op_definition
class ConcatOp(IRDLOperation):
    """Concatenate qubit references: ``quake.concat %a, %b : (...) -> !quake.veq<?>``."""

    name = "quake.concat"
    operands_ = var_operand_def(AnyAttr())
    result = result_def(QuakeVeqType)

    def __init__(self, operands: Sequence[SSAValue]) -> None:
        super().__init__(operands=[operands], result_types=[QuakeVeqType()])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_list(self.operands_, printer.print_ssa_value)
        printer.print_string(" : (")
        printer.print_list(self.operands_, lambda v: printer.print_attribute(v.type))
        printer.print_string(") -> !quake.veq<?>")


# ---------------------------------------------------------------------------
# Quantum gate ops (memory semantics – all side-effecting, no results)
# ---------------------------------------------------------------------------


def _quake_gate_print(self: IRDLOperation, printer: Printer) -> None:  # noqa: N802
    """Shared print logic for all Quake gate ops in memory semantics mode.

    Format (following Quake assembly format)::

        quake.h [%ctrl0] (%param0) %tgt : (param-types, ctrl-types, tgt-types) -> ()

    The type signature uses MLIR's ``functional-type`` format (flat list of all
    SSA operand types in order: parameters, controls, targets) as defined by
    the CUDA-Q Quake dialect's ``AttrSizedOperandSegments`` assemblyFormat.
    """

    # Float parameters
    param_list = list(self.params)
    if param_list:
        printer.print_string(" (")
        printer.print_list(param_list, printer.print_ssa_value)
        printer.print_string(")")

    # Controls
    ctrl_list = list(self.controls)
    if ctrl_list:
        printer.print_string(" [")
        printer.print_list(ctrl_list, printer.print_ssa_value)
        printer.print_string("]")

    # Target qubits (always at least one)
    tgt_list = list(self.targets)
    if tgt_list:
        printer.print_string(" ")
        printer.print_list(tgt_list, printer.print_ssa_value)

    # Type signature: functional-type over ALL SSA operands (params, controls, targets)
    # This matches CUDA-Q's assemblyFormat which uses functional-type(operands, results).
    all_operands = param_list + ctrl_list + tgt_list
    printer.print_string(" : (")
    printer.print_list(all_operands, lambda v: printer.print_attribute(v.type))
    printer.print_string(") -> ()")


def _mk_gate_cls(quake_name: str) -> type:
    """Create an xDSL IRDLOperation subclass for the Quake gate *quake_name*.

    All gate classes share the same operand layout (controls, params, targets)
    and the same :func:`_quake_gate_print` printer.

    Parameters
    ----------
    quake_name:
        Fully-qualified Quake gate name, e.g. ``"quake.h"`` or ``"quake.rx"``.

    Returns
    -------
    type
        A new, irdl-registered subclass of :class:`IRDLOperation`.
    """
    safe_name = quake_name.replace(".", "_").replace("<", "_").replace(">", "")

    ns: dict = {
        "name": quake_name,
        "irdl_options": (AttrSizedOperandSegments(),),
        "controls": var_operand_def(AnyAttr()),
        "params": var_operand_def(AnyAttr()),
        "targets": var_operand_def(AnyAttr()),
        "print": _quake_gate_print,
    }
    cls = type(f"_Quake_{safe_name}Op", (IRDLOperation,), ns)
    return irdl_op_definition(cls)


def _gate_init(
    cls: type,
    controls: Sequence[SSAValue],
    params: Sequence[SSAValue],
    targets: Sequence[SSAValue],
) -> IRDLOperation:
    """Instantiate a Quake gate op (used by the factory helper :func:`make_gate_op`)."""
    return cls(operands=[list(controls), list(params), list(targets)])


# Pre-built gate op classes indexed by Quake gate name (after stripping "quake." prefix).
# e.g. "h" → QuakeHGateOp class, "s<adj>" → QuakeSAdjGateOp class
_QUAKE_GATE_CLASSES: dict[str, type] = {}

for _gname in [
    # 1-qubit, 0-param
    "h",
    "x",
    "y",
    "z",
    "s",
    "t",
    # 1-qubit, 1-param
    "rx",
    "ry",
    "rz",
    "r1",
    # 1-qubit, 3-param
    "u3",
    # 2-qubit, 0-param
    "swap",
    # Adjoint forms
    "s<adj>",
    "t<adj>",
]:
    _QUAKE_GATE_CLASSES[_gname] = _mk_gate_cls(f"quake.{_gname}")


def make_gate_op(
    gate_name: str,
    controls: Sequence[SSAValue],
    params: Sequence[SSAValue],
    targets: Sequence[SSAValue],
) -> IRDLOperation | None:
    """Instantiate a Quake gate op for the given Jasp *gate_name*.

    Parameters
    ----------
    gate_name:
        Jasp gate name (e.g. ``"h"``, ``"cx"``, ``"rz"``).
    controls:
        SSA values for the control qubits (may be empty).
    params:
        SSA values for the floating-point gate parameters (may be empty).
    targets:
        SSA values for the target qubits.

    Returns
    -------
    IRDLOperation | None
        A new Quake gate op instance, or *None* if the gate is not supported.
    """
    from qrisp.jasp.mlir.quake_lowering.jasp_to_quake.gate_mapping import GATE_MAP

    gate_info = GATE_MAP.get(gate_name)
    if gate_info is None:
        return None

    quake_gate = gate_info.quake_gate  # e.g. "x" for "cx", "s<adj>" for "s_dg"
    cls = _QUAKE_GATE_CLASSES.get(quake_gate)
    if cls is None:
        return None

    return _gate_init(cls, controls, params, targets)


# ---------------------------------------------------------------------------
# Measure, discriminate, reset
# ---------------------------------------------------------------------------


@irdl_op_definition
class MzOp(IRDLOperation):
    """Measure in the Z basis.

    - Single qubit: ``quake.mz %ref : (!quake.ref) -> !quake.measure``
    - Register:     ``quake.mz %veq : (!quake.veq<?>) -> !cc.stdvec<!quake.measure>``

    Per the CUDA-Q Quake dialect, measuring a ``veq`` returns
    ``!cc.stdvec<!quake.measure>`` — a CC span of single-qubit measurement
    values, matching the CUDA-Q reference output.
    """

    name = "quake.mz"
    qubit = operand_def(AnyAttr())
    result = result_def(AnyAttr())

    def __init__(self, qubit: SSAValue) -> None:
        # Choose result type based on whether we're measuring a single qubit or a veq.
        if isinstance(qubit.type, QuakeVeqType):
            # Veq measurement → !cc.stdvec<!quake.measure>
            from qrisp.jasp.mlir.quake_lowering.cc_dialect import CcStdVecType

            result_type = CcStdVecType()
        else:
            result_type = QuakeMeasureType()
        super().__init__(operands=[qubit], result_types=[result_type])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_ssa_value(self.qubit)
        printer.print_string(" : (")
        printer.print_attribute(self.qubit.type)
        if isinstance(self.qubit.type, QuakeVeqType):
            # Emit the literal string to avoid xDSL ParametrizedAttribute printing
            # issues (missing element type) across different xDSL versions.
            printer.print_string(") -> !cc.stdvec<!quake.measure>")
        else:
            printer.print_string(") -> ")
            printer.print_attribute(self.result.type)


@irdl_op_definition
class DiscriminateOp(IRDLOperation):
    """Convert a measurement to a classical value.

    - Single: ``quake.discriminate %meas : (!quake.measure) -> i1``
    - Multi:  ``quake.discriminate %meas : (!quake.measurements<?>) -> i1``

    The CUDA-Q Quake spec allows ``discriminate`` to accept either
    ``!quake.measure`` (single-qubit) or ``!quake.measurements<N>``
    (multi-qubit) as its input.  Using ``AnyAttr()`` for the operand
    constraint accommodates both ``QuakeMeasureType`` and
    ``QuakeMeasurementsType`` without requiring a common base class.
    The actual type is reflected accurately in the printed output.
    """

    name = "quake.discriminate"
    meas = operand_def(AnyAttr())  # QuakeMeasureType or QuakeMeasurementsType
    result = result_def(i1)

    def __init__(self, meas: SSAValue) -> None:
        super().__init__(operands=[meas], result_types=[i1])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_ssa_value(self.meas)
        printer.print_string(" : (")
        printer.print_attribute(self.meas.type)
        printer.print_string(") -> i1")


@irdl_op_definition
class ResetOp(IRDLOperation):
    """Reset a qubit to |0⟩: ``quake.reset %ref : (!quake.ref) -> ()``."""

    name = "quake.reset"
    qubit = operand_def(AnyAttr())

    def __init__(self, qubit: SSAValue) -> None:
        super().__init__(operands=[qubit])

    def print(self, printer: Printer) -> None:
        printer.print_string(" ")
        printer.print_ssa_value(self.qubit)
        printer.print_string(" : (")
        printer.print_attribute(self.qubit.type)
        printer.print_string(") -> ()")


# ---------------------------------------------------------------------------
# Dialect registration
# ---------------------------------------------------------------------------

_ALL_GATE_CLASSES = list(_QUAKE_GATE_CLASSES.values())


class QuakeDialect(Dialect):
    """Minimal xDSL dialect for the CUDA-Q Quake dialect (memory semantics)."""

    name = "quake"
    operations = [
        AllocaRefOp,
        AllocaVeqOp,
        DeallocOp,
        ExtractRefOp,
        VeqSizeOp,
        SubVeqOp,
        ConcatOp,
        MzOp,
        DiscriminateOp,
        ResetOp,
        *_ALL_GATE_CLASSES,
    ]
    attributes = [QuakeRefType, QuakeVeqType, QuakeMeasureType]
