"""
/********************************************************************************
* Copyright (c) 2023 the Qrisp authors
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License 2.0 which is available at
* http://www.eclipse.org/legal/epl-2.0.
*
* This Source Code may also be made available under the following Secondary
* Licenses when the conditions for such availability set forth in the Eclipse
* Public License, v. 2.0 are satisfied: GNU General Public License, version 2 
* or later with the GNU Classpath Exception which is
* available at https://www.gnu.org/software/classpath/license.html.
*
* SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0
********************************************************************************/
"""

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class Qubit(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, identifier=None):  # noqa: E501
        """Qubit - a model defined in OpenAPI

        :param identifier: The identifier of this Qubit.  # noqa: E501
        :type identifier: str
        """
        self.openapi_types = {
            'identifier': str
        }

        self.attribute_map = {
            'identifier': 'identifier'
        }

        self._identifier = identifier

    @classmethod
    def from_dict(cls, dikt) -> 'Qubit':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Qubit of this Qubit.  # noqa: E501
        :rtype: Qubit
        """
        return util.deserialize_model(dikt, cls)

    @property
    def identifier(self):
        """Gets the identifier of this Qubit.


        :return: The identifier of this Qubit.
        :rtype: str
        """
        return self._identifier

    @identifier.setter
    def identifier(self, identifier):
        """Sets the identifier of this Qubit.


        :param identifier: The identifier of this Qubit.
        :type identifier: str
        """
        if identifier is None:
            raise ValueError("Invalid value for `identifier`, must not be `None`")  # noqa: E501

        self._identifier = identifier
