"""
********************************************************************************
* Copyright (c) 2026 the Qrisp authors
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License 2.0 which is available at
* http://www.eclipse.org/legal/epl-2.0.
*
* This Source Code may also be made available under the following Secondary
* Licenses when the conditions for such availability set forth in the Eclipse
* Public License, v. 2.0 are satisfied: GNU General Public License, version 2
* with the GNU Classpath Exception which is
* available at https://www.gnu.org/software/classpath/license.html.
*
* SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
********************************************************************************
"""

import numpy as np
import pytest
from qrisp.algorithms.gqsp.gqsp_angles import (
    poly_to_nlft_sequence,
    gqsp_angles,
    qsp_angles,
    qsvt_angles,
    xqsp_angles,
    yqsp_angles,
    _xqsp_angles_from_nlft_sequence,
    _yqsp_angles_from_nlft_sequence,
)
from qrisp.algorithms.gqsp.gqsp_angles_verification import (
    assert_gqsp_angles_match_target,
    assert_nlft_sequence_match_target,
    assert_qsp_angles_match_target,
    assert_qsvt_angles_match_target,
)


@pytest.mark.parametrize(
    "target_coeffs",
    [
        np.array([0.0, 1.1, 0.0, -1.0, 0.4, 0.7, 0.4, 0.4, 0.6]),
        np.array([0.0, 0.5, 0.0, 0.25]),
        np.array([0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([1.3, 0.3, 0.2, 0.1, 0.9, -0.4, 0.6, 0.3]),
        np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([0.1, 0.3, 0.0, -0.2, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
    ],
)
def test_gqsp_polynomial(target_coeffs):
    """Test that the angles generated by gqsp_angles correctly reconstruct the target polynomial."""

    (gqsp_theta, gqsp_phi, gqsp_lambda), alpha = gqsp_angles(target_coeffs)

    assert_gqsp_angles_match_target(
        theta_angles=gqsp_theta,
        phi_angles=gqsp_phi,
        lambd=gqsp_lambda,
        alpha=alpha,
        target_coeffs=target_coeffs,
        atol=1e-5,
    )


@pytest.mark.parametrize(
    "target_coeffs",
    [
        np.array([0.0, 0.5, 0.0, 0.25]),
        np.array([0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([1.3, 0.3, 0.2, 0.1, 0.9, -0.4, 0.6, 0.3]),
        np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([0.1, 0.3, 0.0, -0.2, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
    ],
)
def test_nlft_sequence(target_coeffs):
    """Test that the NLFT sequence generated by poly_to_nlft_sequence correctly reconstructs the target polynomial."""

    F, alpha = poly_to_nlft_sequence(target_coeffs)

    # This will silently pass if successful, or raise AssertionError if failed
    assert_nlft_sequence_match_target(F_sequence=F, alpha=alpha, target_coeffs=target_coeffs, atol=1e-5)


@pytest.mark.parametrize(
    "target_coeffs, parity",
    [
        (np.array([0.5, 0.5, 0.0, 0.25]), "odd"),
        (np.array([0.0, 0.0, 0.0, 0.0, 1.0]), "even"),
        (np.array([1.3, 0.3, 0.2, 0.1, 0.9, -0.4, 0.6, 0.3]), "even"),
        (np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), "even"),
        (np.array([0.1, 0.3, 0.0, -0.2, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), "even"),
    ],
)
def test_qsp_angles(target_coeffs, parity):
    """Test that the angles generated by qsp_angles correctly reconstruct the target polynomial for both even and odd parity cases."""

    # For comparing against the target coefficients, we need to zero out the coefficients that do not match the specified parity
    if parity.lower() == "odd":
        # Zero out the even indices (0, 2, 4...)
        target_coeffs[0::2] = 0.0
    elif parity.lower() == "even":
        # Zero out the odd indices (1, 3, 5...)
        target_coeffs[1::2] = 0.0
    else:
        raise ValueError("Parity must be either 'even' or 'odd'.")

    # Replace with your actual generated angles
    angles, alpha = qsp_angles(target_coeffs, parity=parity)  # Use the provided parity

    # Testing Z-QSP (W_z signal, S_x phase)
    assert_qsp_angles_match_target(
        angles=angles, alpha=alpha, target_cheb_coeffs=target_coeffs, signal_basis="Z", phase_basis="X", atol=1e-5
    )


@pytest.mark.parametrize(
    "target_coeffs, parity",
    [
        (np.array([0.5, 0.5, 0.0, 0.25]), "odd"),
        (np.array([0.0, 0.0, 0.0, 0.0, 1.0]), "even"),
        (np.array([1.3, 0.3, 0.2, 0.1, 0.9, -0.4, 0.6, 0.3]), "even"),
        (np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), "even"),
        (np.array([0.1, 0.3, 0.0, -0.2, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]), "even"),
    ],
)
def test_qsvt_angles(target_coeffs, parity):
    """Test that the angles generated by qsvt_angles correctly reconstruct the target polynomial for both even and odd parity cases."""

    # For comparing against the target coefficients, we need to zero out the coefficients that do not match the specified parity
    if parity.lower() == "odd":
        # Zero out the even indices (0, 2, 4...)
        target_coeffs[0::2] = 0.0
    elif parity.lower() == "even":
        # Zero out the odd indices (1, 3, 5...)
        target_coeffs[1::2] = 0.0
    else:
        raise ValueError("Parity must be either 'even' or 'odd'.")

    # Replace with your actual generated angles
    angles, alpha = qsvt_angles(target_coeffs, parity=parity)  # Use the provided parity

    # Testing Z-QSP (W_z signal, S_x phase)
    assert_qsvt_angles_match_target(angles=angles, alpha=alpha, target_cheb_coeffs=target_coeffs, atol=1e-5)


def test_xqsp_angles_unimplemented():
    """Test that the xqsp_angles function raises NotImplementedError."""
    with pytest.raises(NotImplementedError):
        _xqsp_angles_from_nlft_sequence(np.array([1.0, 0.0, 0.0]))

    with pytest.raises(NotImplementedError):
        xqsp_angles(np.array([1.0, 0.0, 0.0]))


def test_yqsp_angles_unimplemented():
    """Test that the yqsp_angles function raises NotImplementedError."""
    with pytest.raises(NotImplementedError):
        _yqsp_angles_from_nlft_sequence(np.array([1.0, 0.0, 0.0]))

    with pytest.raises(NotImplementedError):
        yqsp_angles(np.array([1.0, 0.0, 0.0]))
