"""
********************************************************************************
* Copyright (c) 2026 the Qrisp authors
*
* This program and the accompanying materials are made available under the
* terms of the Eclipse Public License 2.0 which is available at
* http://www.eclipse.org/legal/epl-2.0.
*
* This Source Code may also be made available under the following Secondary
* Licenses when the conditions for such availability set forth in the Eclipse
* Public License, v. 2.0 are satisfied: GNU General Public License, version 2
* with the GNU Classpath Exception which is
* available at https://www.gnu.org/software/classpath/license.html.
*
* SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
********************************************************************************
"""

import numpy as np
import pytest
from qrisp.algorithms.gqsp.gqsp_angles import (
    poly_to_nlft_sequence,
    gqsp_angles,
    xqsp_angles,
    yqsp_angles,
)
from qrisp.algorithms.gqsp.gqsp_angles_verification import (
    assert_gqsp_angles_match_target,
    assert_nlft_sequence_match_target,
    evaluate_gqsp_polynomial,
    evaluate_nlft_sequence,
)


@pytest.mark.parametrize(
    "target_coeffs",
    [
        np.array([0.0, 1.1, 0.0, -1.0, 0.4, 0.7, 0.4, 0.4, 0.6]),
        np.array([0.0, 0.5, 0.0, 0.25]),
        np.array([0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([1.3, 0.3, 0.2, 0.1, 0.9, -0.4, 0.6, 0.3]),
        np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([0.1, 0.3, 0.0, -0.2, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
    ],
)
def test_gqsp_polynomial(target_coeffs):
    """Test that the angles generated by gqsp_angles correctly reconstruct the target polynomial."""

    (gqsp_theta, gqsp_phi, gqsp_lambda), alpha = gqsp_angles(target_coeffs)

    assert_gqsp_angles_match_target(
        theta_angles=gqsp_theta,
        phi_angles=gqsp_phi,
        lambd=gqsp_lambda,
        alpha=alpha,
        target_coeffs=target_coeffs,
        atol=1e-5,
    )


@pytest.mark.parametrize(
    "target_coeffs",
    [
        np.array([0.0, 0.5, 0.0, 0.25]),
        np.array([0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([1.3, 0.3, 0.2, 0.1, 0.9, -0.4, 0.6, 0.3]),
        np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
        np.array([0.1, 0.3, 0.0, -0.2, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]),
    ],
)
def test_nlft_sequence(target_coeffs):
    """Test that the NLFT sequence generated by poly_to_nlft_sequence correctly reconstructs the target polynomial."""

    F, alpha = poly_to_nlft_sequence(target_coeffs)

    # This will silently pass if successful, or raise AssertionError if failed
    assert_nlft_sequence_match_target(
        F_sequence=F, alpha=alpha, target_coeffs=target_coeffs, atol=1e-5
    )
