name: Docs Build

on:
  pull_request:
    paths:
      - 'documentation/**'
      - 'src/qrisp/**'
      - 'pyproject.toml'
      - '.readthedocs.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y pandoc
          pip install -e ".[docs]"
      - name: Build documentation
        run: |
          sphinx-build -b html documentation/source documentation/build/html
