name: Link Checker

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
  schedule:
    - cron: "00 18 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12.*"
          cache: 'pip'

      - name: Install dependencies
        run: |
          make docs-install
        working-directory: documentation

      - name: Check links with Sphinx linkcheck
        run: |
          make linkcheck SPHINXOPTS="-W"
        working-directory: documentation

      - name: Check standalone files with lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: >
            --verbose --no-progress
            './README.md'
            './src/**/*.md'
            './.github/pull_request_template.md'
            './src/**/*.py'
            './tests/**/*.py'
          fail: true
