name: Main pipeline for linting and testing

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.*"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run pre-commit
        # FIXME: Does only run on subset of files since not all files are linted yet
        run: pre-commit run --files pyproject.toml .pre-commit-config.yaml requirements/* --show-diff-on-failure

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        python-version: ["3.10.*"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Test with pytest
        run: pytest
