name: Qrisp unit tests via Pytest

on:
  push:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      matrix:
        python-version: ["3.11.*"]

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest qiskit-aer qiskit-iqm pyscf stim cirq xdsl
          pip install -e ./
          pip install --upgrade pennylane-catalyst gast
          pip install git+https://github.com/tqec/tqecd.git 
          pip install qiskit-aer
          pip install qiskit-ibm-runtime   # To test `QiskitBackend` with `qiskit_ibm_runtime.fake_provider`
          pip install iqm-client[qiskit]
          pip install pyscf
          pip install stim
          pip install xdsl
          pip install 'numpy<2.3'          # To solve 'ImportError: Numba needs NumPy 2.3 or less.'
      - name: Test with pytest
        run: |
          pytest
