name: Code style checks

on:
  push:
    branches:
      - main
      - Enable_Python_3.13_in_the_CI_pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ["3.12.*", "3.13.*"]
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev-code-style]"
      - name: Ruff format
        uses: astral-sh/ruff-action@v3
        with:
          args: format --check
      # - name: Ruff linter
      #   uses: astral-sh/ruff-action@v3
      #   with:
      #     args: check  # wait for fix from Niko's student
